### ISSUE TITLE
npm run serve – "Not found"

### ISSUE THREAD

**Issue by MichaelTrilford-Airwallex** [lit/lit-element-starter-js#19]
Is there a known problem with the provided template, or is it user error? These are the exact steps I'm following.

1. `lit-element-starter-js-master npm i`

2. `npm i`
<img width="280" alt="Screen Shot 2021-07-24 at 4 19 22 pm" src="https://user-images.githubusercontent.com/75596057/126859581-e3243c74-25cb-4716-88f9-182d1cc7e8ed.png">

3. `npm run serve`
<img width="384" alt="Screen Shot 2021-07-24 at 4 19 30 pm" src="https://user-images.githubusercontent.com/75596057/126859537-e1ff2723-b96b-4e4c-9fc5-c5f28878d504.png">

4. Success
<img width="294" alt="Screen Shot 2021-07-24 at 4 20 17 pm" src="https://user-images.githubusercontent.com/75596057/126859545-a0161bd0-d79a-48e2-b9e7-2bd6289a27af.png">

5. Not found
<img width="784" alt="Screen Shot 2021-07-24 at 4 15 47 pm" src="https://user-images.githubusercontent.com/75596057/126859461-7b99f8bd-9845-4cec-bd3d-6659a2c23225.png">

**Comment by MichaelTrilford-Airwallex** [comment]
I found the problem.

If I follow the CLI instructions localhost instructions I get the error:
<img width="217" alt="Screen Shot 2021-07-25 at 2 13 30 pm" src="https://user-images.githubusercontent.com/75596057/126887491-7c80e018-4812-432a-9ebc-6450e45d07c4.png">

I should be adding /dev to the URL:
E.g. `http://localhost:8000/dev`

<img width="715" alt="Screen Shot 2021-07-25 at 2 09 39 pm" src="https://user-images.githubusercontent.com/75596057/126887428-3b49c661-fd68-4e09-bd64-77bb5d90a183.png">

Would it be bad practice to include the /dev on the local host URL in the CLI? Potentially a better experience?

**Comment by claymation** [comment]
The Web Dev Server appears to be configured to serve files from `docs`:

```
$ npm run serve

> @lit/lit-starter-js@1.0.0 serve
> wds --watch

Web Dev Server started...

  Root dir: /home/clay/lit-element-starter-js-main/docs
  Local:    http://localhost:8000/
  Network:  http://10.10.10.10:8000/
```

which is incompatible with the instructions:

> There is a development HTML file located at `/dev/index.html` that you can view at http://localhost:8000/dev/index.html.

Not having read the README, I tried navigating to http://localhost:8000/, which worked fine, but then I was confused as to why I had to run `npm run docs` to rebuild the `docs/my-element.bundled.js` bundle whenever I made a change.

Should the Web Dev Server just be configured to serve from `.` rather than from `docs`?

**Comment by AndrewJakubowicz** [comment]
This should be addressed after [this change](https://github.com/lit/lit/commit/8b9dcb4d10e4161083146ae40d0b12174a63d31d) is released.

There is a bug where currently `npm run serve` is serving the documentation directory instead of your demo.

I'll follow up on this thread once the starter kits have had a new release.
Thank you!

**Comment by AndrewJakubowicz** [comment]
Sorry for the slow turnaround. Could you try and reproduce this issue again now that https://github.com/lit/lit-element-starter-js/commit/af17a326a09360760b297c395b3bc1a54f1cebf5 has been merged. Let me know if that change resolves the issue.

Thank you!

**Comment by claymation** [comment]
It works, thanks.
